"use client";
import { Alert, Button, Group, Paper, Stack, Text, TextInput } from "@mantine/core";
export function ConversationThread({ conversation, loading, error, onBack, mobile }) {
  if (loading) return <Paper withBorder p="md"><Text c="dimmed">Loading conversation…</Text></Paper>;
  if (error) return <Paper withBorder p="md"><Text c="red.7">Unable to load this conversation.</Text></Paper>;
  if (!conversation) return <Paper withBorder p="md"><Text c="dimmed">Select a conversation to view its retained messages.</Text></Paper>;
  const composerEnabled = conversation.status === "human_active";
  return <Paper withBorder p="md" radius="md" style={{ minWidth: 0, overflow: "hidden" }}><Group justify="space-between" mb="sm">{mobile ? <Button variant="subtle" size="xs" onClick={onBack}>Back to inbox</Button> : <Text fw={600}>{conversation.customerLabel}</Text>}<Text size="xs" c="dimmed">{conversation.status}</Text></Group>{conversation.status === "resolved" ? <Alert color="green" mb="sm">This conversation is resolved.</Alert> : null}{conversation.status === "waiting_human" ? <Alert color="orange" mb="sm">Waiting for a human owner.</Alert> : null}{conversation.deliveryFailed ? <Alert color="red" mb="sm">A delivery issue needs attention.</Alert> : null}<Stack gap="xs" mih={220} style={{ overflowY: "auto" }}>{conversation.messages.map((message) => <Paper key={message.id} p="xs" bg={message.direction === "outbound" ? "blue.0" : "gray.0"} ml={message.direction === "outbound" ? "auto" : 0} style={{ maxWidth: "88%" }}><Text size="xs" c="dimmed">{message.senderType}</Text><Text style={{ whiteSpace: "pre-wrap" }}>{message.text || "Unsupported message type"}</Text></Paper>)}</Stack><Group mt="md" wrap="nowrap"><TextInput aria-label="Reply composer" placeholder={composerEnabled ? "Replying is available in the next step" : "Activate human handling to reply"} disabled style={{ flex: 1, minWidth: 0 }} /><Button disabled={!composerEnabled}>Send</Button></Group></Paper>;
}
